services:
  server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      HOME: /home/nonroot
      K8S_CONFIG_PATH: ${K8S_CONFIG_PATH:-/home/nonroot/.kube/config}
      MODE: ${MODE:-dev}
      PORT: ${PORT:-8080}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ${HOME}/.kube:/home/nonroot/.kube:ro
